[server]
enableCORS = false
enableXsrfProtection = false
enableStaticServing = true
runOnSave = false
debug = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"

[client]
showErrorDetails = false

[runner]
installTracer = false