[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"

[client]
client.showErrorDetails = false
client.showWarningDetails = false
client.displayEnabled = false

[runner]
installTracer = false