version: 1.19.0

components:
  - name: DocumentStore # How you want to call this node here
    type: ElasticsearchDocumentStore # This is the Haystack node class
    params: # The node parameters
      embedding_dim: 384 # This parameter is required for the embedding_model
  - name: Retriever
    type: EmbeddingRetriever
    params:
      document_store: DocumentStore
      top_k: 10
      embedding_model: sentence-transformers/all-MiniLM-L6-v2
  - name: FileTypeClassifier
    type: FileTypeClassifier
  - name: TextFileConverter
    type: TextConverter
  - name: Preprocessor
    type: PreProcessor
    params: # These parameters define how you want to split your documents
      split_by: word
      split_length: 250
      split_overlap: 30 
      split_respect_sentence_boundary: True 

pipelines:
  - name: query 
    nodes:
      - name: Retriever
        inputs: [Query]
  - name: indexing  
    nodes:
      - name: FileTypeClassifier
        inputs: [File]
      - name: TextFileConverter
        inputs: [FileTypeClassifier.output_1]
      - name: Preprocessor
        inputs: [TextFileConverter]
      - name: Retriever
        inputs: [Preprocessor]
      - name: DocumentStore
        inputs: [Retriever]