name: Deploy to DigitalOcean

on:
  push:
    branches:
      - uat

jobs:

  Clone-brockai: 
    runs-on: ubuntu-latest
    steps:
      - name: Clone brockai repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DROPLET_IP}}
          username: root
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            rm -rf ./brockai
            git clone https://github.com/brockai/brockai.git

  Start-Streamlit:
    runs-on: ubuntu-latest
    needs: Clone-brockai
    steps:
      - name: Setup service, python env and run Streamlit app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # turn off streamlit service, copy service config, reload daemon
            sudo systemctl stop streamlit-uat.service || true
            cp ./brockai/streamlit-uat.service /etc/systemd/system/streamlit-uat.service
            sudo systemctl daemon-reload

            # remove existing app, copy over cloned app
            rm /var/www/streamlit-uat -r || true
            mkdir /var/www/streamlit-uat || true
            cp .env /var/www/streamlit-uat
            cp ./brockai/frontend/. -r /var/www/streamlit-uat
            cd /var/www/streamlit-uat

            # create python env, install requirements, restart streamlit-uat service
            sudo python3 -m venv brockai-uat
            source brockai-uat/bin/activate
            pip install -r requirements.txt
            sudo systemctl start streamlit-uat.service
