name: Deploy Production

on:
  push:
    branches:
      - main

jobs:

  Clone-brockai: 
    runs-on: ubuntu-latest
    steps:
      - name: Clone brockai repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DROPLET_IP}}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            git clone -b main https://github.com/brockai/brockai.git

  Setup-Streamlit-Python:
    runs-on: ubuntu-latest
    needs: Clone-brockai
    steps:
      - name: Setup streamlit service & python env
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # turn off streamlit service, copy service config, reload daemon
            sudo systemctl stop streamlit.service || true
            cp ./brockai/config/streamlit.service /etc/systemd/system/streamlit.service
            sudo systemctl daemon-reload

            # remove existing app, copy over cloned app
            rm /var/www/streamlit -r || true
            mkdir /var/www/streamlit || true
            cp .env /var/www/streamlit
            cp ./brockai/frontend/. -r /var/www/streamlit
            cd /var/www/streamlit

            # create python env & install requirements
            sudo python3 -m venv brockai
            source brockai/bin/activate
            pip install -r requirements.txt

  Start-Streamlit:
    runs-on: ubuntu-latest
    needs: Setup-Streamlit-Python
    steps:
      - name: Restart Streamlit
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf /root/brockai
            sudo systemctl restart streamlit.service 
            sudo systemctl restart streamlit-uat.service           





