name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:

  Clone-Python: 

    runs-on: ubuntu-latest

    steps:

      - name: Clone brockai repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DROPLET_IP}}
          username: root
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            rm -rf ./brockai
            git clone https://github.com/brockai/brockai.git

      - name: Install python
        uses: appleboy/ssh-action@master
        with:
           host: ${{ secrets.DROPLET_IP }}
           username: ${{ secrets.DROPLET_USERNAME }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
             sudo apt update
             sudo apt install python3
             sudo apt-get -y install python3.11-venv

  Remove-OpenSearch:
    runs-on: ubuntu-latest
    needs: Clone-Python
    steps:
      - name: Remove Existing OpenSearch Services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker system prune --all --force --volumes
            docker stop opensearch-node1 || true
            docker stop opensearch-node2 || true
            docker stop opensearch-dashboards || true
            docker compose down || true

  Start-OpenSearch-Node1:
    runs-on: ubuntu-latest
    needs: Remove-OpenSearch
    steps:
      - name: Build opensearch-node1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/brockai
            docker compose up -d opensearch-node1 || true            
          
  Start-OpenSearch-Node2:
    runs-on: ubuntu-latest
    needs: Start-OpenSearch-Node1
    steps:
      - name: Build opensearch-node2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/brockai
            docker compose up -d opensearch-node2 || true                             

  Start-OpenSearch-Dashboards:
    runs-on: ubuntu-latest
    needs: Start-OpenSearch-Node2
    steps:
      - name: Build opensearch-dashboards
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/brockai
              docker compose up -d opensearch-dashboards || true     

  Start-Streamlit:
    runs-on: ubuntu-latest
    needs: Start-OpenSearch-Dashboards
    steps:
      - name: Setup service, python env and run Streamlit app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # turn off streamlit service, copy service config, reload daemon
            sudo systemctl stop streamlit.service || true
            cp ./brockai/streamlit.service /etc/systemd/system/streamlit.service
            sudo systemctl daemon-reload

            # remove existing app, copy over cloned app
            rm /var/www/streamlit -r || true
            mkdir /var/www/streamlit || true
            cp .env /var/www/streamlit
            cp ./brockai/frontend/. -r /var/www/streamlit
            cd /var/www/streamlit

            # create python env, install requirements, restart streamlit service
            sudo python3 -m venv brockai
            source brockai/bin/activate
            pip install -r requirements.txt
            sudo systemctl start streamlit.service || true

  Nginx-Reverse-Proxy:
    runs-on: ubuntu-latest
    needs: Start-Streamlit
    steps:
      - name: Install nginx & reverse-proxy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo apt-get -y purge nginx nginx-common
            sudo apt update
            sudo apt-get -y install nginx
            sudo cp -f /root/brockai/default.conf /etc/nginx/sites-available/default -f
            sudo cp -f /root/brockai/reverse-proxy.conf /etc/nginx/sites-available/reverse-proxy.conf
            sudo ln -s /etc/nginx/sites-available/reverse-proxy.conf /etc/nginx/sites-enabled/
            sudo nginx -t
            sudo systemctl restart nginx
            sudo systemctl enable nginx            

