name: Deploy Production

on:
  push:
    branches:
      - main

jobs:

  Clone-brockai: 
    runs-on: ubuntu-latest
    steps:
      - name: Clone brockai repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DROPLET_IP}}
          username: root
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            rm -rf ./brockai
            git clone https://github.com/brockai/brockai.git

  Start-Streamlit:
    runs-on: ubuntu-latest
    needs: Clone-brockai
    steps:
      - name: Setup service, python env and run Streamlit app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # turn off streamlit service, copy service config, reload daemon
            sudo systemctl stop streamlit.service || true
            cp ./brockai/streamlit.service /etc/systemd/system/streamlit.service
            sudo systemctl daemon-reload

            # remove existing app, copy over cloned app
            rm /var/www/streamlit -r || true
            mkdir /var/www/streamlit || true
            cp .env /var/www/streamlit
            cp ./brockai/frontend/. -r /var/www/streamlit
            cd /var/www/streamlit

            # create python env, install requirements, restart streamlit service
            sudo python3 -m venv brockai
            source brockai/bin/activate
            pip install -r requirements.txt
            sudo systemctl start streamlit.service





