name: Deploy Production

on:
  push:
    branches:
      - main

jobs:

  Clone-brockai: 
    runs-on: ubuntu-latest
    steps:
      - name: Clone brockai repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DROPLET_IP}}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            rm -rf /root/brockai
            git clone -b main https://github.com/brockai/brockai.git

  Setup-Streamlit-Python:
    runs-on: ubuntu-latest
    needs: Clone-brockai
    steps:
      - name: Setup streamlit service, python env & run streamlit
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # turn off streamlit service, copy service config, reload daemon
            sudo systemctl stop streamlit.service || true
            cp ./brockai/config/streamlit.service /etc/systemd/system/streamlit.service
            sudo systemctl daemon-reload

            # remove existing app, copy over cloned app
            rm /var/www/streamlit -r || true
            mkdir /var/www/streamlit || true
            cp .env /var/www/streamlit
            cp ./brockai/frontend/. -r /var/www/streamlit

            # create python env, install requirements, start streamlit
            sudo python3 -m venv /var/www/streamlit-uat/brockai
            source /var/www/streamlit/brockai/bin/activate

            pip install -r /var/www/streamlit/requirements.txt

            sudo systemctl restart streamlit.service || true  






