name: Deploy User Acceptance Testing

on:
  push:
    branches:
      - uat

jobs:

  Clone-brockai: 
    runs-on: ubuntu-latest
    steps:
      - name: Clone brockai repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DROPLET_IP}}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            rm -rf /root/brockai
            git clone -b uat https://github.com/brockai/brockai.git

  Setup-Streamlit-Python:
    runs-on: ubuntu-latest
    needs: Clone-brockai
    steps:
      - name: Setup service & python env
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # turn off streamlit service, copy service config, reload daemon
            sudo systemctl stop streamlit-uat.service || true
            cp /root/brockai/config/streamlit-uat.service /etc/systemd/system/streamlit-uat.service
            sudo systemctl daemon-reload

            # remove existing app, copy over cloned app
            rm /var/www/streamlit-uat -r || true
            mkdir /var/www/streamlit-uat || true--port
            cp /root/.env /var/www/streamlit-uat
            cp /root/brockai/frontend/. -r /var/www/streamlit-uat

            # create python env & install requirements
            sudo python3 -m venv /var/www/streamlit-uat/brockai-uat
            source /var/www/streamlit-uat/brockai-uat/bin/activate
            pip install -r /var/www/streamlit-uat/requirements.txt
            cd /var/www/streamlit-uat
            streamlit run app.py --server.port 8502  
            
  # Start-Streamlit:
  #   runs-on: ubuntu-latest
  #   needs: Setup-Streamlit-Python
  #   steps:
  #     - name: Restart Streamlit
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.DROPLET_IP }}
  #         username: ${{ secrets.DROPLET_USERNAME }}
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         script: |
  #           cd /var/www/streamlit-uat
  #           streamlit run app.py --server.port 8502  
  #           # sudo systemctl restart streamlit-uat.service
  #           # sudo systemctl daemon-reload